name: air-contaminant
services:
  streamlit:
    build:
      context: . # in root directory
      dockerfile: ./docker/streamlit/dockerfile
    image: indraps30/ac_streamlit # Docker_Hub_Username/Docker_Image_Name
    container_name: streamlit_frontend
    depends_on:
      - api # streamlit baru bisa berjalan ketika api sudah berjalan.
    ports:
      - "8501:8501" # Host:Container

  api:
    build:
      context: .
      dockerfile: ./docker/api/dockerfile
    image: indraps30/ac_api
    container_name: api_backend
    ports:
      - "8080:8080"